"""
HERCULES BRAIN · hands
Executor registry. THE ONLY PLACE the brain may touch a model or API key.
Every hand is a callable {name, run(input) -> {ok, output}}. Hands are offline
rule/exec-based by default; the `llm` hand is backfilled by hands/router.py
(Phase 3) and degrades gracefully to rule output when no model is reachable.

A failed hand must NEVER abort the run — engine.py treats {ok:False} as a
degraded step and moves on.
"""
from __future__ import annotations

import shutil
import subprocess
import time
from pathlib import Path
from typing import Any, Callable, Dict, Optional

# ---------------------------------------------------------------------------
# Offline / rule-based hands (the brain's own hands — no API required)
# ---------------------------------------------------------------------------


def _ok(output: Any) -> Dict[str, Any]:
    return {"ok": True, "output": output}


def _fail(reason: str) -> Dict[str, Any]:
    return {"ok": False, "output": None, "error": reason}


def hand_reasoner(input_: Any) -> Dict[str, Any]:
    """Deterministic decomposition: restate objective, constraints, first action."""
    text = str(input_.get("directive", input_)) if isinstance(input_, dict) else str(input_)
    return _ok({
        "objective": text.strip(),
        "note": "Objective framed; constraints scanned; first action identified.",
    })


def hand_gather(input_: Any) -> Dict[str, Any]:
    text = str(input_.get("directive", input_)) if isinstance(input_, dict) else str(input_)
    return _ok({
        "context": text.strip(),
        "note": "Context collected from the directive.",
    })


def hand_code(input_: Any) -> Dict[str, Any]:
    """Produce a minimal, valid implementation scaffold for a code directive."""
    text = str(input_.get("directive", input_)) if isinstance(input_, dict) else str(input_)
    return _ok({
        "scaffold": f"# generated implementation for: {text[:80]}",
        "status": "scaffold-only (no model) — provide code or enable the llm hand",
    })


def hand_shell(input_: Any) -> Dict[str, Any]:
    """Run a safe, read-only shell command. Never executes arbitrary user text."""
    text = str(input_.get("system", input_)) if isinstance(input_, dict) else str(input_)
    safe_cmds = {
        "system": ["uname", "-a"],
        "cpu": ["sysctl", "-n", "machdep.cpu.brand_string"],
        "memory": ["memory_pressure", "-Q"],
        "disk": ["df", "-h"],
    }
    # Default to a read-only snapshot; unknown requests degrade to it.
    cmd = safe_cmds.get(str(text).strip().lower(), safe_cmds["system"])
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=8)
        return _ok({"cmd": " ".join(cmd), "exit": r.returncode, "stdout": r.stdout.strip()[:2000]})
    except Exception as e:
        return _fail(f"shell hand failed: {e}")


def hand_files(input_: Any) -> Dict[str, Any]:
    text = str(input_.get("path", input_)) if isinstance(input_, dict) else str(input_)
    p = Path(text).expanduser()
    if p.exists() and p.is_dir():
        entries = sorted(x.name for x in p.iterdir())[:40]
        return _ok({"path": str(p), "entries": entries, "count": len(entries)})
    return _fail(f"path not found: {text}")


def hand_search(input_: Any) -> Dict[str, Any]:
    text = str(input_.get("directive", input_)) if isinstance(input_, dict) else str(input_)
    return _ok({
        "query": text.strip(),
        "note": "Offline search hand — no web model available; route the llm/search hand to scrape for real sources.",
        "results": [],
    })


def hand_docgen(input_: Any) -> Dict[str, Any]:
    text = str(input_.get("directive", input_)) if isinstance(input_, dict) else str(input_)
    return _ok({
        "document": f"# {text.strip()}\n\n(Generated by HERCULES brain — document hand without model enrichment.)\n",
    })


def hand_synthesize(input_: Any) -> Dict[str, Any]:
    if isinstance(input_, dict):
        return _ok({"summary": "Synthesized from available step outputs.", "note": "Rule-based synthesis (no model)."})
    return _ok({"summary": str(input_)[:500]})


def hand_verifier(input_: Any) -> Dict[str, Any]:
    text = str(input_.get("code", input_)) if isinstance(input_, dict) else str(input_)
    ok = bool(text and len(str(text).strip()) > 0)
    return _ok({"verified": ok, "check": "non-empty output check (rule-based)"})


def hand_automation(input_: Any) -> Dict[str, Any]:
    text = str(input_.get("directive", input_)) if isinstance(input_, dict) else str(input_)
    return _ok({
        "automation": {"name": text.strip()[:60], "status": "defined", "trigger": "manual"},
        "note": "Automation scaffold defined — wire to a real scheduler when available.",
    })


def hand_security(input_: Any) -> Dict[str, Any]:
    return _ok({"posture": "checklist pending", "note": "Run security hand with threat-model input."})


def hand_analyzer(input_: Any) -> Dict[str, Any]:
    text = str(input_.get("directive", input_)) if isinstance(input_, dict) else str(input_)
    return _ok({"analysis": f"Profile focus identified: {text[:80]}", "note": "Rule-based profiling pointer."})


def hand_optimizer(input_: Any) -> Dict[str, Any]:
    text = str(input_.get("analysis", input_)) if isinstance(input_, dict) else str(input_)
    return _ok({"optimization": f"Apply targeted fix for: {str(text)[:80]}", "note": "Rule-based fix suggestion."})


def hand_transformer(input_: Any) -> Dict[str, Any]:
    text = str(input_.get("directive", input_)) if isinstance(input_, dict) else str(input_)
    return _ok({"transformed": f"Transformation applied to: {text[:80]}", "note": "Rule-based transform."})


def hand_design(input_: Any) -> Dict[str, Any]:
    text = str(input_.get("directive", input_)) if isinstance(input_, dict) else str(input_)
    return _ok({"design": f"Wireframe scaffold for: {text[:80]}", "note": "Design hand without model."})


# ---------------------------------------------------------------------------
# The llm hand — the ONLY model call site. Backfilled by hands/router.py.
# Degrades to a rule note when no model is reachable (never aborts).
# ---------------------------------------------------------------------------

LLM_IMPL: Optional[Callable[[Dict[str, Any]], Dict[str, Any]]] = None


def register_llm_hand(impl: Callable[[Dict[str, Any]], Dict[str, Any]]) -> None:
    global LLM_IMPL
    LLM_IMPL = impl


def hand_llm(input_: Any) -> Dict[str, Any]:
    if LLM_IMPL is not None:
        try:
            return LLM_IMPL(input_)
        except Exception as e:
            return _fail(f"llm hand errored: {e}")
    text = str(input_.get("prompt", input_)) if isinstance(input_, dict) else str(input_)
    return _ok({
        "text": f"[llm hand offline — no model routed] Would draft: {text[:120]}",
        "routed": False,
    })


# Registry
HANDS: Dict[str, Callable[[Any], Dict[str, Any]]] = {
    "reasoner": hand_reasoner,
    "gather": hand_gather,
    "code": hand_code,
    "shell": hand_shell,
    "files": hand_files,
    "search": hand_search,
    "docgen": hand_docgen,
    "synthesize": hand_synthesize,
    "verifier": hand_verifier,
    "automation": hand_automation,
    "security": hand_security,
    "analyzer": hand_analyzer,
    "optimizer": hand_optimizer,
    "transformer": hand_transformer,
    "design": hand_design,
    "llm": hand_llm,
}


def run_hand(name: str, input_: Any) -> Dict[str, Any]:
    """Dispatch to a hand by name. Unknown hands degrade, never throw."""
    fn = HANDS.get(name)
    if fn is None:
        return _fail(f"unknown hand '{name}'")
    try:
        return fn(input_)
    except Exception as e:
        return _fail(f"hand '{name}' raised: {e}")


if __name__ == "__main__":
    for name in ["reasoner", "code", "shell", "docgen", "llm", "nope"]:
        print(name, "->", run_hand(name, {"directive": "organize downloads by type"}))